#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Apr 19 11:03:38 2021

@author: harry
"""

import numpy as np
import pandas as pd
import Meteo_data_shape_weather as mds

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split




dataset_1=pd.read_csv('/home/harry/Documents/projet_station_meteo/NW_Ground_Stations/Meteo_NW_2016.csv')
dataset_2=pd.read_csv('/home/harry/Documents/projet_station_meteo/NW_Ground_Stations/Meteo_NW_2017.csv')
dataset_3=pd.read_csv('/home/harry/Documents/projet_station_meteo/NW_Ground_Stations/Meteo_NW_2018.csv')
dataset=pd.concat([dataset_1, dataset_2, dataset_3], axis=0)

data=mds.Meteo_Data_View(dataset, hours=1, days=3, dropping=[], view=6 )
data_meteo=data.data_good_shape
cible_direction=data.target_direction

model=RandomForestClassifier()
X_train, X_test, y_train, y_test=train_test_split(data_meteo, cible_direction)

model.fit(X_train, y_train)
print(model.score(X_train, y_train))
print(model.score(X_test, y_test))


